version: '3'

services:
  app:
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    command: /opt/venv/bin/python /app/src/manage.py runserver 0.0.0.0:8000