# Generated by Django 4.2.11 on 2025-08-13 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_user_username_remove_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Hero', max_length=255)),
                ('faction', models.CharField(choices=[('The Crusaders', 'The Crusaders'), ('The Moors', 'The Moors')], max_length=50)),
                ('race', models.CharField(choices=[('Castilian', 'Castilian'), ('Aragonese', 'Aragonese'), ('Leonese', 'Leonese'), ('Andalusian', 'Andalusian'), ('Berber', 'Berber'), ('Mashriqi', 'Mashriqi')], max_length=50)),
                ('character_class', models.CharField(choices=[('Knight', 'Knight'), ('Arbalist', 'Arbalist'), ('Skirmisher', 'Skirmisher'), ('Blade Dancer', 'Blade Dancer'), ('Alchemist', 'Alchemist'), ('Mystic Poet', 'Mystic Poet')], max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='one_active_character_per_user'),
        ),
    ]
